[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Tiger Analytics"
authors = [{name = "Tiger Analytics", email = "example@tiger"}]
dynamic = ["version", "description"]
